import { Color3 } from "@babylonjs/core";

/** Presentation-only tuning values; changing these never affects GameState coordinates or stats. */
export const VISUAL_CONFIG = {
  /** Rendered character size only; grid occupancy and combat ranges stay unchanged. */
  unitVisualScaleMultiplier: 1.5,
  allyScaleMultiplier: 2.295,
  /** Presentation-only breathing room inside a tile; logical footprint stays one grid cell. */
  defenderVisualScaleMultiplier: 0.75,
  /** Presentation-only size accents; gameplay footprint stays exactly one tile at every level. */
  towerLevelScaleMultipliers: { 1: 1, 2: 1.12, 3: 1.24 },
  selectedTowerRingDiameter: 0.95,
  selectedTowerRingThickness: 0.09,
  selectedTowerRingPulseSeconds: 1.4,
  selectedTowerRingBaseAlpha: 0.88,
  selectedTowerRingPulseAlpha: 0.08,
  selectedTowerMarkerSize: 0.22,
  selectedTowerMarkerOffset: 0.42,
  selectedTowerMarkerBobAmplitude: 0.075,
  selectedTowerMarkerFallbackHeight: 1.8,
  spawnGoalMarkerSize: 1,
  arcaneCoreColor: Color3.FromHexString("#5B4CFF"),
  arcaneGlowColor: Color3.FromHexString("#4DA8FF"),
  arcaneHighlightColor: Color3.FromHexString("#9BE8FF"),
  arcaneProjectileDiameter: 0.16,
  arcaneHaloDiameter: 0.32,
  arcaneArcHeight: 0.32,
  arcaneMinFlightSeconds: 0.10,
  arcaneMaxFlightSeconds: 0.22,
  arcaneFlightSecondsPerUnit: 0.012,
  arcaneBurstDuration: 0.20,
  arcaneMaxProjectiles: 32,
  arcaneMaxBursts: 16,
  enemyScaleMultiplier: 2.125,
  enemyMaxDimension: 5,
  defaultCameraRadius: 25.5,
  defaultCameraBeta: 0.86,
  defaultCameraAlpha: Math.PI / 2,
  defaultCameraTargetX: 39,
  minCameraRadius: 13.5,
  maxCameraRadius: 70,
  cameraPanSpeed: 1,
  cameraPanZoomMultiplier: 0.18,
  desktopDragThreshold: 8,
  touchDragThreshold: 12,
  cameraPanMargin: 0.75,
  /** Thin vertex-colour overlay; alpha is applied per grid vertex for reliable mobile blending. */
  gridColor: new Color3(0.55, 0.50, 0.43),
  gridAlpha: 0.11,
  buildGridAlpha: 0.24,
  buildVisualHoldMs: 1100,
  snowBaseColor: new Color3(0.88, 0.95, 1),
  royalGroundBaseColor: new Color3(0.98, 0.95, 0.87),
  royalCliffTint: new Color3(0.97, 0.94, 0.88),
  royalAmbientColor: new Color3(0.91, 0.89, 0.83),
  royalShadowColor: new Color3(0.36, 0.37, 0.33),
  royalSunColor: new Color3(1, 0.94, 0.82),
  royalAmbientIntensity: 0.58,
  royalDirectionalIntensity: 0.86,
  royalFogDensity: 0.00135,
  snowSpecularColor: new Color3(0.14, 0.23, 0.3),
  snowSpecularPower: 34,
  frostColor: new Color3(0.48, 0.69, 0.8),
  frostAlpha: 0.105,
  packedSnowColor: new Color3(0.82, 0.88, 0.9),
  packedSnowAlpha: 0.1,
  validPlacementColor: new Color3(0.16, 0.9, 0.67),
  invalidPlacementColor: new Color3(0.95, 0.18, 0.16),
  selectedCellColor: new Color3(0.28, 0.78, 1),
  selectedTowerRingColor: Color3.FromHexString("#BFFFFF"),
  placementAlpha: 0.34,
  spawnGlowStrength: 0.95,
  exitGlowStrength: 0.82,
  gateLightRange: 4.8,
  environmentDensity: 0.72,
  fogDensity: 0.0022,
  outskirtsTreeScale: 1.55,
  outskirtsRockScale: 0.95,
  outskirtsSmallPropScale: 0.34,
  outskirtsWagonScale: 0.58,
  outskirtsFenceScale: 0.72,
  outskirtsWallScale: 1.1,
  outskirtsCrateScale: 0.62,
  outskirtsMaxPropWidth: 3.2,
  outskirtsMaxPropHeight: 4.5,
  outskirtsMaxPropDepth: 3.2,
  outskirtsClusterBedRadius: 1.8,
  warmOutskirtsLightIntensity: 0.28,
  warmOutskirtsLightRange: 3.2,
  snowAmbientColor: new Color3(0.8, 0.9, 1),
  snowShadowColor: new Color3(0.14, 0.22, 0.31),
  snowSunColor: new Color3(0.86, 0.93, 1),
  ambientIntensity: 0.54,
  directionalIntensity: 0.76,
  allyAccentColor: new Color3(0.12, 0.68, 0.88),
} as const;
