import { Color3 } from "@babylonjs/core";

/** Presentation-only tuning values; changing these never affects GameState coordinates or stats. */
export const VISUAL_CONFIG = {
  allyScaleMultiplier: 2.295,
  /** Presentation-only breathing room inside a tile; logical footprint stays one grid cell. */
  defenderVisualScaleMultiplier: 0.75,
  /** Presentation-only size accents; gameplay footprint stays exactly one tile at every level. */
  towerLevelScaleMultipliers: { 1: 1, 2: 1.12, 3: 1.24 },
  selectedTowerRingDiameter: 0.95,
  selectedTowerRingThickness: 0.09,
  selectedTowerRingPulseSeconds: 1.4,
  selectedTowerRingBaseAlpha: 0.88,
  selectedTowerRingPulseAlpha: 0.08,
  selectedTowerMarkerSize: 0.22,
  selectedTowerMarkerOffset: 0.42,
  selectedTowerMarkerBobAmplitude: 0.075,
  selectedTowerMarkerFallbackHeight: 1.8,
  spawnGoalMarkerSize: 1,
  arcaneCoreColor: Color3.FromHexString("#5B4CFF"),
  arcaneGlowColor: Color3.FromHexString("#4DA8FF"),
  arcaneHighlightColor: Color3.FromHexString("#9BE8FF"),
  arcaneProjectileDiameter: 0.16,
  arcaneHaloDiameter: 0.32,
  arcaneArcHeight: 0.32,
  arcaneMinFlightSeconds: 0.10,
  arcaneMaxFlightSeconds: 0.22,
  arcaneFlightSecondsPerUnit: 0.012,
  arcaneBurstDuration: 0.20,
  arcaneMaxProjectiles: 32,
  arcaneMaxBursts: 16,
  enemyScaleMultiplier: 2.125,
  enemyMaxDimension: 5,
  defaultCameraRadius: 25.5,
  defaultCameraBeta: 0.86,
  defaultCameraAlpha: Math.PI / 2,
  defaultCameraTargetX: 39,
  minCameraRadius: 13.5,
  maxCameraRadius: 38,
  cameraPanSpeed: 1,
  cameraPanZoomMultiplier: 0.18,
  desktopDragThreshold: 8,
  touchDragThreshold: 12,
  cameraPanMargin: 0.75,
  gridColor: new Color3(0.62, 0.73, 0.78),
  gridAlpha: 0.015,
  buildGridAlpha: 0.10,
  buildVisualHoldMs: 1100,
  snowBaseColor: new Color3(0.68, 0.78, 0.84),
  snowSpecularColor: new Color3(0.14, 0.23, 0.3),
  snowSpecularPower: 34,
  frostColor: new Color3(0.48, 0.69, 0.8),
  frostAlpha: 0.105,
  packedSnowColor: new Color3(0.82, 0.88, 0.9),
  packedSnowAlpha: 0.1,
  validPlacementColor: new Color3(0.16, 0.9, 0.67),
  invalidPlacementColor: new Color3(0.95, 0.18, 0.16),
  selectedCellColor: new Color3(0.28, 0.78, 1),
  selectedTowerRingColor: Color3.FromHexString("#BFFFFF"),
  placementAlpha: 0.34,
  spawnGlowStrength: 0.95,
  exitGlowStrength: 0.82,
  gateLightRange: 4.8,
  environmentDensity: 0.72,
  fogDensity: 0.0022,
  outskirtsTreeScale: 0.36,
  outskirtsRockScale: 0.48,
  outskirtsSmallPropScale: 0.34,
  outskirtsMaxPropWidth: 3.2,
  outskirtsMaxPropHeight: 4.5,
  outskirtsMaxPropDepth: 3.2,
  outskirtsClusterBedRadius: 1.8,
  warmOutskirtsLightIntensity: 0.28,
  warmOutskirtsLightRange: 3.2,
  ambientIntensity: 0.48,
  directionalIntensity: 0.82,
  allyAccentColor: new Color3(0.12, 0.68, 0.88),
} as const;
